// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// Rails Example
import HelloController from "./hello_controller"
application.register("hello", HelloController)

import DynamicSubcategoryController from "./dynamic_subcategory_controller"
application.register("dynamic_subcategory", DynamicSubcategoryController)

import AccordionIconController from "./accordion_icon_controller"
application.register("accordion_icon", AccordionIconController)
